plugins { id 'com.android.application' }
android {
    namespace 'dev.lilt.player'
    compileSdk 35
    defaultConfig { applicationId 'dev.lilt.player'; minSdk 26; targetSdk 35; versionCode 30; versionName '1.22' }
    buildTypes { release { debuggable false } }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
dependencies {
    implementation 'androidx.media3:media3-exoplayer:1.5.1'
    implementation 'androidx.media3:media3-session:1.5.1'
}
